### ISSUE TITLE
update to websocket changes by Tibber?

### ISSUE THREAD

**Issue by humpataa** [gulars/Tibber-Realtime-Kw-Meter#1]
Hello, very interesting script! Have you tried to adapt your script to the changes that Tibber has made to their websocket usage?
Any hint is appreciated!

**Comment by gulars** [comment]
Yes, I have, will update tomorrow.

søn. 26. feb. 2023, 15:06 skrev Dan Dyse ***@***.***>:

**Comment by humpataa** [comment]
Thank you for the quick reply Jonas - I have tried changing the script at jsFiddle:
- changed URL to "wss://websocket-api.tibber.com/v1-beta/gql/subscriptions"
- changed websocket to "graphql-transport-ws"
- changed token to Demo-Key "5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE" and homeId to "96a14971-525a-4420-aae9-e5aedaa129ff"

But it still doesn't seem to work - what am I missing?

**Comment by gulars** [comment]
jsFiddle is updated, you can have a look,  it has some new verbs

**Comment by gulars** [comment]
I close this, hope you will have fun with it.
